CREATE DATABASE IF NOT EXISTS crud;

CREATE TABLE IF NOT EXISTS crud.employees(
    ID int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    UserName VARCHAR(255),
    Email VARCHAR(255)
) DEFAULT CHARSET UTF8 COMMENT 'Employees data';